[package]
name = "merkle"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10" 
serde = "1.0"

[dev-dependencies]
rand = "0.8.5"
criterion = { version = "0.5.1" }
bincode = "1.3"
hex = "0.4"

[[bench]]
name = "merkle_tree"
harness = false